---
- hosts: dc1lab002
  tasks:

  - name: Insall epel repo  
    yum: name=epel-release state=present
 
  - name: install patches for database
    yum: name={{item}} state=present
    with_items:
    - gcc*
    - libaio-devel.x86_64
    
  - name: Install telnet
    yum: name=telnet* state=present

  
  