---
### Demo ansible scipt
### For testing if a process is running and depending on that do the next action
### Developed by Mohammad Tariq Ayub. mohammad.tariq.ayub@outlook.com Date 08/04/2017

- hosts: dc2lab002
  become_user: root

  tasks:
    # Purpose of this to check if an pplication is running of stopped
    - name: Verify application/database are running or not
      shell: if ps -eaf | egrep 'apache|httpd' | grep -v grep >/dev/null ; then echo 'process_running' ; else echo 'process_not_running'; fi 
      ignore_errors: true
      register: app_process_check

    # This task will take decision, Will fail/quit, if application is running
    - name: decision point to start patching
      fail: msg="{{ inventory_hostname }} have running application. Please stop the application first, then attempt patching"
      when: app_process_check.stdout == "process_running"

    # This will upgrade/install the rpm's if the application is stopped
    - name : upgrade all packages on the server
      yum:
        name="kernel"
        state=latest
      when: app_process_check.stdout == "process_not_running" and ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'OracleLinux'
      register: yum_update 

    # This will check if kernel update happened and system needs a reboot or not
    - name: check if reboot required after kernel update
      shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' |sed 's/kernel-//') ; KERNEL_NOW=$(uname -r) ; if [[ $KERNEL_NEW != $KERNEL_NOW ]] ; then echo "reboot_needed" ; else echo "reboot_not_needed"; fi
      ignore_errors: true
      register: reboot_required

    # This task is to restart system